const colors = {
    white: "#FFFFFF",
    whiteLilac: "#FBFBFE",
    slateGray: "#6E7E91",
    scienceBlue: "#0366D6",
    mineShaft: "#252525",
    iron: "#E5E5E5",
    semiDark: "#363636",
    dodgerBlue: "#2188FF",
    semiGray: "rgba(54, 54, 54, 0.72)",
    malibu: "#5CA8FF",
};

const breakpoints = {
    mobile: "767px",
    tablet: "991px",
    narrow: "1199px",
};

export const themeLight = {
    color: {
        mainBackground: colors.whiteLilac,
        listText: colors.slateGray,
        sectionBackground: colors.white,
        sectionTitle: colors.mineShaft,
        titleUnderline: colors.iron,
        buttonLinkBackground: colors.scienceBlue,
        buttonLinkName: colors.white,
        thisIs: colors.slateGray,
        aboutMe: colors.slateGray,
        switchButton: colors.slateGray,
        projectName: colors.scienceBlue,
        projectTileBackground: colors.white,
        projectDescription: colors.slateGray,
        projectLink: colors.scienceBlue,
        letsTalk: colors.slateGray,
        contact: colors.mineShaft,
        icons: colors.mineShaft,
        emailHover: colors.scienceBlue,
        iconHover: colors.scienceBlue,
        switchSun: colors.white,
        switchBackground: colors.iron,
        switchBorder: colors.semiGray,
        switchIconWrapper: colors.slateGray,
        infoLoading: colors.mineShaft,
        errorText: colors.mineShaft,
        linkHover: colors.dodgerBlue,
    },
    breakpoint: {
        mobile: breakpoints.mobile,
        tablet: breakpoints.tablet,
        narrow: breakpoints.narrow,
    },
};

export const themeDark = {
    color: {
        mainBackground: colors.mineShaft,
        listText: colors.white,
        sectionBackground: colors.semiDark,
        sectionTitle: colors.white,
        titleUnderline: colors.iron,
        buttonLinkBackground: colors.dodgerBlue,
        buttonLinkName: colors.white,
        thisIs: colors.white,
        aboutMe: colors.white,
        switchButton: colors.white,
        projectName: colors.white,
        projectTileBackground: colors.semiGray,
        projectDescription: colors.white,
        projectLink: colors.dodgerBlue,
        letsTalk: colors.white,
        contact: colors.white,
        icons: colors.white,
        emailHover: colors.dodgerBlue,
        iconHover: colors.dodgerBlue,
        switchSun: colors.mineShaft,
        switchBackground: colors.semiGray,
        switchBorder: colors.white,
        switchIconWrapper: colors.white,
        infoLoading: colors.white,
        errorText: colors.white,
        linkHover: colors.malibu,
    },
    breakpoint: {
        mobile: breakpoints.mobile,
        tablet: breakpoints.tablet,
        narrow: breakpoints.narrow,
    },
};